"""Structured representation of a MongoDB query generated by the LLM."""

from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator


class GeoNear(BaseModel):
    """A "nearby" request as data (coordinates + a requested radius), not as raw Mongo
    $near/$geoNear syntax -- the LLM can't get operator shape, coordinate order, or an
    unbounded radius wrong if it never writes the operator itself. Same trust model as
    start_date/end_date below: the model describes intent, code translates it (see
    app/db/executor.py) and enforces bounds (see MAX_GEO_RADIUS_M in app/rag/validator.py)."""

    field: str = "location"
    longitude: float
    latitude: float
    max_distance_m: float


class QuerySpec(BaseModel):
    collection: str
    operation: Literal["find", "aggregate", "count"]
    filter: dict = Field(default_factory=dict)
    pipeline: list[dict] = Field(default_factory=list)
    projection: dict | None = None
    sort: dict | None = None
    limit: int = 50
    start_date: str | None = None
    end_date: str | None = None
    geo_near: GeoNear | None = None
    # Set independently of geo_near: a domain agent may know the question asked for "within 5km"
    # without knowing real coordinates for a named place/person/id (see app/agents/query_agents.py
    # geo rule) -- code that later resolves those coordinates (app/agents/graph.py) reuses this
    # as the requested radius instead of guessing one.
    requested_radius_m: float | None = None

    @model_validator(mode="before")
    @classmethod
    def _coerce_explicit_nulls_to_defaults(cls, data: Any) -> Any:
        """Confirmed in production: the model sometimes emits "limit": null (and could just as
        easily do the same for filter/pipeline) rather than omitting the field or using the
        concrete example value shown in the prompt -- likely pattern-matching the several
        genuinely-optional null fields nearby (start_date, end_date, geo_near). A field default
        in Pydantic only applies when the key is *absent*, not when it's explicitly null, so this
        was hard-failing the whole question on a benign, non-adversarial LLM quirk instead of
        just falling back to the default like a missing key would. Only fields with a real
        default need this -- geo_near/projection/sort/etc. are meant to be nullable already."""
        if not isinstance(data, dict):
            return data
        defaults: dict[str, Any] = {"filter": {}, "pipeline": [], "limit": 50}
        for field, default in defaults.items():
            if data.get(field) is None:
                data[field] = default
        return data


class QueryError(BaseModel):
    """Returned instead of a QuerySpec when the question can't be answered from the data."""

    error: str
