"""Structured representation of a MongoDB query generated by the LLM."""

from typing import Literal

from pydantic import BaseModel, Field


class QuerySpec(BaseModel):
    collection: str
    operation: Literal["find", "aggregate", "count"]
    filter: dict = Field(default_factory=dict)
    pipeline: list[dict] = Field(default_factory=list)
    projection: dict | None = None
    sort: dict | None = None
    limit: int = 50
    start_date: str | None = None
    end_date: str | None = None


class QueryError(BaseModel):
    """Returned instead of a QuerySpec when the question can't be answered from the data."""

    error: str
